[package]
name = "enclave-policies"
edition.workspace = true
version.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
license.workspace = true
readme.workspace = true

[dependencies]
attestation-service = { workspace = true }
base64 = { workspace = true }
anyhow = { workspace = true }

[lints]
workspace = true
