[workspace]
resolver = "2"
members = [
    "crates/attestation-rpc",
    "crates/attestation-service",
    "crates/custodian-ipc",
    "crates/enclave-contract", "crates/enclave",
    "crates/enclave-crypto",
    "crates/key-custodian",
    "crates/key-custodian-host",
    "crates/network-manifest",
    "crates/seismic-attestation",
    "crates/tdx-init",
]

[workspace.package]
edition = "2024"
version = "0.1.0"
repository = "https://github.com/SeismicSystems/enclave"
homepage = "https://github.com/SeismicSystems/enclave"
authors = ["Seismic Systems"]
license = "MIT"
readme = "README.md"

[workspace.dependencies]
# workspace libs
enclave-contract = { path = "crates/enclave-contract" }
seismic-attestation = { path = "crates/seismic-attestation" }
seismic-attestation-rpc = { path = "crates/attestation-rpc" }
seismic-custodian-ipc = { path = "crates/custodian-ipc" }
seismic-enclave = {path = "crates/enclave" }
seismic-enclave-crypto = { path = "crates/enclave-crypto" }
seismic-key-custodian = { path = "crates/key-custodian" }
seismic-key-custodian-host = { path = "crates/key-custodian-host" }
seismic-network-manifest = { path = "crates/network-manifest" }

# Other deps
alloy = "1.0"
aes-gcm = "0.10"
anyhow = "1.0"
attestation = { git = "https://github.com/flashbots/attested-tls", rev = "05a79a3f16a6d074bc10ce7aa29a3cd804fdc613" }
az-cvm-vtpm = { version = "0.7.4", default-features = false }
az-tdx-vtpm = "0.7.4"
bincode = "1.3.3"
ciborium = "0.2"
clap = { version = "4.5.51", features = ["derive", "env"] }
dcap-rs = "0.1.0"
base64-url = "3.0.0"
thiserror = "2.0"
hex = "0.4.3"
hkdf = "0.12"
jsonrpsee = { version = "0.26.0", features = ["server", "client","macros"] }
libc = "0.2.177"
rand = "0.9.2"
reqwest = { version = "0.11", features = ["json"] }
schnorrkel = { version = "0.11.2", features = ["serde"] }
secp256k1 = { version = "0.30", features = ["rand", "recovery", "std", "serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_bytes = "0.11"
serde_json = "1.0"
sha2 = "0.10.9"
tokio = { version = "1.44", features = ["full"] }
tracing = { version = "0.1.41"}
tracing-subscriber = { version = "0.3", default-features = false, features = ["env-filter", "fmt", "ansi", "json"] }
zeroize = "1.8.1"
