//! Generate and verify an Azure TDX + vTPM attestation through the
//! `seismic-attestation` policy wrapper.
//!
//! Run on an Azure TDX CVM with vTPM access. It checks that the attestation
//! backend can produce Azure evidence and verify its quoted PCRs against a
//! `make measure` output.
//!
//! Example:
//!   cargo run -p seismic-attestation --example azure_vtpm_roundtrip -- \
//!     --measurements /path/to/seismic-images/build/measurements.json
//!
//! For debugging without enforcing PCR values, use:
//!   cargo run -p seismic-attestation --example azure_vtpm_roundtrip -- --accept-any

#[cfg(target_os = "linux")]
use clap::Parser;

#[cfg(target_os = "linux")]
#[derive(Debug, Parser)]
struct Args {
    /// Measurements JSON generated by `seismic-images make measure`.
    ///
    /// Expected format is the cvm-reverse-proxy/attested-tls format with an
    /// `azure-tdx` entry and PCR values such as 4, 9, and 11.
    #[arg(long, conflicts_with = "accept_any")]
    measurements: Option<std::path::PathBuf>,

    /// Accept any Azure TDX PCR measurements. Useful only to inspect the actual
    /// PCRs returned by the verifier before a measurements file exists.
    #[arg(long)]
    accept_any: bool,

    /// Optional PCCS URL for DCAP collateral. If omitted, the attestation
    /// backend uses its default DCAP collateral path.
    #[arg(long)]
    pccs_url: Option<String>,

    /// Optional 64-byte attestation input as hex. If omitted, a deterministic
    /// demo input is used. In production this must bind a nonce/transcript/TLS
    /// channel; do not reuse this default.
    #[arg(long)]
    input_hex: Option<String>,

    /// Write the generated raw attestation document to this path before
    /// verification. Useful for inspecting AK certificates and HCL claims when
    /// verification fails.
    #[arg(long)]
    write_evidence: Option<std::path::PathBuf>,

    /// Allow the Azure outdated-TCB override path.
    ///
    /// This exists as a workaround for some Azure v6 TCB collateral. Leave false
    /// unless you are specifically testing that environment.
    #[arg(long)]
    override_azure_outdated_tcb: bool,
}

#[cfg(target_os = "linux")]
#[tokio::main]
async fn main() -> anyhow::Result<()> {
    use seismic_attestation::{
        AttestationType, SeismicMeasurementPolicy, VerifyOptions, generate_evidence,
        verify_evidence_with_options,
    };

    let args = Args::parse();
    let input_data = parse_or_default_input(args.input_hex.as_deref())?;

    let measurement_policy = if args.accept_any {
        SeismicMeasurementPolicy::dangerously_accept_any_for_testing(AttestationType::AzureTdx)
    } else {
        let Some(path) = args.measurements else {
            anyhow::bail!("pass --measurements <file> or --accept-any");
        };
        SeismicMeasurementPolicy::from_json_bytes(&tokio::fs::read(path).await?)?
    };

    println!("Generating Azure TDX + vTPM attestation...");
    let evidence = generate_evidence(AttestationType::AzureTdx, input_data)?;
    println!(
        "Generated {} evidence: {} bytes",
        evidence.attestation_type,
        evidence.attestation.len()
    );

    if let Some(path) = &args.write_evidence {
        std::fs::write(path, &evidence.attestation)?;
        println!("Wrote raw Azure attestation document to {}", path.display());
    }

    println!("Verifying Azure TDX + vTPM attestation...");
    let verified = verify_evidence_with_options(
        evidence,
        input_data,
        measurement_policy,
        VerifyOptions {
            pccs_url: args.pccs_url,
            dump_dcap_quotes: false,
            override_azure_outdated_tcb: args.override_azure_outdated_tcb,
        },
    )
    .await?;
    println!("Verification succeeded.");
    println!("Verified Seismic attestation: {verified:#?}");

    Ok(())
}

#[cfg(target_os = "linux")]
fn parse_or_default_input(input_hex: Option<&str>) -> anyhow::Result<[u8; 64]> {
    if let Some(input_hex) = input_hex {
        let bytes = hex::decode(input_hex.trim_start_matches("0x"))?;
        return bytes.try_into().map_err(|bytes: Vec<u8>| {
            anyhow::anyhow!("--input-hex must be 64 bytes, got {}", bytes.len())
        });
    }

    // Deterministic demo-only input. First half is the TPM quote nonce used by
    // The Azure backend uses the first half as the TPM quote nonce; full 64
    // bytes are also placed into HCL user-data.
    let mut input = [0u8; 64];
    input[..32].copy_from_slice(b"seismic-demo-azure-vtpm-input!!!");
    input[32..].copy_from_slice(b"do-not-use-this-in-production!!!");
    Ok(input)
}

#[cfg(not(target_os = "linux"))]
fn main() {
    eprintln!("azure_vtpm_roundtrip must be run on a Linux Azure TDX CVM");
    std::process::exit(1);
}
