//! Generate and verify an Azure TDX + vTPM attestation using Flashbots'
//! experimental Rust `attestation` crate.
//!
//! Run on an Azure TDX CVM with vTPM access. This is a spike/example, not yet a
//! Seismic production verifier. It checks that the Flashbots crate can produce
//! Azure evidence and verify its quoted PCRs against a `make measure` output.
//!
//! Example:
//!   cargo run -p seismic-attestation --example flashbots_azure_vtpm_roundtrip -- \
//!     --measurements /path/to/seismic-images/build/measurements.json
//!
//! For debugging without enforcing PCR values, use:
//!   cargo run -p seismic-attestation --example flashbots_azure_vtpm_roundtrip -- --accept-any

#[cfg(target_os = "linux")]
use clap::Parser;

#[cfg(target_os = "linux")]
#[derive(Debug, Parser)]
struct Args {
    /// Measurements JSON generated by `seismic-images make measure`.
    ///
    /// Expected format is the cvm-reverse-proxy/attested-tls format with an
    /// `azure-tdx` entry and PCR values such as 4, 9, and 11.
    #[arg(long, conflicts_with = "accept_any")]
    measurements: Option<std::path::PathBuf>,

    /// Accept any Azure TDX PCR measurements. Useful only to inspect the actual
    /// PCRs returned by the verifier before a measurements file exists.
    #[arg(long)]
    accept_any: bool,

    /// Optional PCCS URL for DCAP collateral. If omitted, the Flashbots
    /// attestation crate uses its default DCAP collateral path.
    #[arg(long)]
    pccs_url: Option<String>,

    /// Optional 64-byte attestation input as hex. If omitted, a deterministic
    /// demo input is used. In production this must bind a nonce/transcript/TLS
    /// channel; do not reuse this default.
    #[arg(long)]
    input_hex: Option<String>,

    /// Write the generated raw attestation document to this path before
    /// verification. Useful for inspecting AK certificates and HCL claims when
    /// verification fails.
    #[arg(long)]
    write_evidence: Option<std::path::PathBuf>,

    /// Allow Flashbots' Azure outdated-TCB override path.
    ///
    /// This exists because their crate carries a workaround for some Azure v6
    /// TCB collateral. Leave false unless you are specifically testing that
    /// environment.
    #[arg(long)]
    override_azure_outdated_tcb: bool,
}

#[cfg(target_os = "linux")]
#[tokio::main]
async fn main() -> anyhow::Result<()> {
    use attestation::{
        AttestationGenerator, AttestationType, AttestationVerifier, measurements::MeasurementPolicy,
    };

    let args = Args::parse();
    let input_data = parse_or_default_input(args.input_hex.as_deref())?;

    let measurement_policy = if args.accept_any {
        MeasurementPolicy::single_attestation_type(AttestationType::AzureTdx)
    } else {
        let Some(path) = args.measurements else {
            anyhow::bail!("pass --measurements <file> or --accept-any");
        };
        MeasurementPolicy::from_file(path).await?
    };

    println!("Generating Azure TDX + vTPM attestation...");
    let generator = AttestationGenerator::new(AttestationType::AzureTdx, None)?;
    let evidence = generator.generate_attestation(input_data)?;
    println!(
        "Generated {} evidence: {} bytes",
        evidence.attestation_type,
        evidence.attestation.len()
    );

    if let Some(path) = &args.write_evidence {
        std::fs::write(path, &evidence.attestation)?;
        println!("Wrote raw Azure attestation document to {}", path.display());
    }

    println!("Verifying Azure TDX + vTPM attestation...");
    let verifier = AttestationVerifier::new(
        measurement_policy,
        args.pccs_url,
        false,
        args.override_azure_outdated_tcb,
    );

    let measurements = verifier.verify_attestation(evidence, input_data).await?;
    println!("Verification succeeded.");
    println!("Verified measurements: {measurements:#?}");

    Ok(())
}

#[cfg(target_os = "linux")]
fn parse_or_default_input(input_hex: Option<&str>) -> anyhow::Result<[u8; 64]> {
    if let Some(input_hex) = input_hex {
        let bytes = hex::decode(input_hex.trim_start_matches("0x"))?;
        return bytes.try_into().map_err(|bytes: Vec<u8>| {
            anyhow::anyhow!("--input-hex must be 64 bytes, got {}", bytes.len())
        });
    }

    // Deterministic demo-only input. First half is the TPM quote nonce used by
    // Flashbots' Azure path; full 64 bytes are also placed into HCL user-data.
    let mut input = [0u8; 64];
    input[..32].copy_from_slice(b"seismic-demo-azure-vtpm-input!!!");
    input[32..].copy_from_slice(b"do-not-use-this-in-production!!!");
    Ok(input)
}

#[cfg(not(target_os = "linux"))]
fn main() {
    eprintln!("flashbots_azure_vtpm_roundtrip must be run on a Linux Azure TDX CVM");
    std::process::exit(1);
}
