[package]
name = "seismic-enclave"
edition.workspace = true
version.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
license.workspace = true
readme.workspace = true

[dependencies]
seismic-crypto.workspace = true

jsonrpsee.workspace = true
schnorrkel.workspace = true
secp256k1.workspace = true
serde.workspace = true
