//! Generate and verify Azure TDX + vTPM evidence through the
//! `seismic-attestation` policy wrapper.
//!
//! Run on an Azure TDX CVM with vTPM access.
//!
//! Roundtrip locally against a `make measure` output:
//!
//! ```text
//! cargo run -p seismic-attestation --example azure_vtpm_roundtrip -- \
//!   roundtrip --measurements /path/to/seismic-images/build/measurements.json
//! ```
//!
//! Capture evidence for offline/remote verification. This writes the full
//! `AttestationExchangeMessage`, not just the backend-specific evidence bytes:
//!
//! ```text
//! cargo run -p seismic-attestation --example azure_vtpm_roundtrip -- \
//!   generate --input-hex <64-byte-hex-binding> --out /tmp/evidence.json
//! ```
//!
//! Verify previously captured evidence:
//!
//! ```text
//! cargo run -p seismic-attestation --example azure_vtpm_roundtrip -- \
//!   verify --input-hex <64-byte-hex-binding> --evidence /tmp/evidence.json \
//!   --measurements /path/to/seismic-images/build/measurements.json
//! ```
//!
//! For debugging without enforcing PCR values, use `--accept-any` on `roundtrip`
//! or `verify`. Both print every quoted PCR as sorted hex, so an actual boot can
//! be compared against a `make measure` prediction, or against another
//! node/boot/build.
//!
//! This example needs local vTPM access, so it only runs on the node itself. To
//! collect the same measurements from a *remote* node over its attestation RPC —
//! including a production node with no shell — use the `capture_measurements`
//! example in `seismic-attestation-service`, which also emits a
//! measurements-file policy record for direct diffing.

#[cfg(target_os = "linux")]
use clap::{Args as ClapArgs, Parser, Subcommand};

#[cfg(target_os = "linux")]
use seismic_attestation::{
    AttestationExchangeMessage, AttestationType, SeismicMeasurementPolicy,
    VerifiedSeismicAttestation, VerifyOptions, generate_evidence, verify_evidence_with_options,
};

#[cfg(target_os = "linux")]
#[derive(Debug, Parser)]
#[command(about = "Generate and verify Azure TDX + vTPM attestation evidence")]
struct Cli {
    #[command(subcommand)]
    command: Command,
}

#[cfg(target_os = "linux")]
#[derive(Debug, Subcommand)]
enum Command {
    /// Generate local Azure evidence and immediately verify it.
    Roundtrip(RoundtripArgs),
    /// Generate local Azure evidence and write the full exchange message.
    Generate(GenerateArgs),
    /// Verify a previously captured full exchange message.
    Verify(VerifyArgs),
}

#[cfg(target_os = "linux")]
#[derive(Debug, ClapArgs)]
struct RoundtripArgs {
    #[command(flatten)]
    binding: BindingArgs,
    #[command(flatten)]
    policy: PolicyArgs,
    #[command(flatten)]
    backend: BackendArgs,
    /// Write the generated full AttestationExchangeMessage to this path before
    /// verification.
    #[arg(long, value_name = "PATH")]
    write_evidence: Option<std::path::PathBuf>,
}

#[cfg(target_os = "linux")]
#[derive(Debug, ClapArgs)]
struct GenerateArgs {
    #[command(flatten)]
    binding: BindingArgs,
    /// Output path for the full AttestationExchangeMessage JSON.
    #[arg(long, value_name = "PATH")]
    out: std::path::PathBuf,
}

#[cfg(target_os = "linux")]
#[derive(Debug, ClapArgs)]
struct VerifyArgs {
    #[command(flatten)]
    binding: BindingArgs,
    #[command(flatten)]
    policy: PolicyArgs,
    #[command(flatten)]
    backend: BackendArgs,
    /// Input path containing a full AttestationExchangeMessage JSON.
    #[arg(long, value_name = "PATH")]
    evidence: std::path::PathBuf,
}

#[cfg(target_os = "linux")]
#[derive(Debug, ClapArgs)]
struct BindingArgs {
    /// Optional 64-byte attestation input as hex. If omitted, a deterministic
    /// demo input is used. In production this must bind a nonce/transcript/TLS
    /// channel; do not reuse this default.
    #[arg(long)]
    input_hex: Option<String>,
}

#[cfg(target_os = "linux")]
#[derive(Debug, ClapArgs)]
struct PolicyArgs {
    /// Measurements JSON generated by `seismic-images make measure`.
    ///
    /// Expected format is the cvm-reverse-proxy/attested-tls format with an
    /// `azure-tdx` entry and PCR values such as 4, 9, and 11.
    #[arg(long, conflicts_with = "accept_any", value_name = "PATH")]
    measurements: Option<std::path::PathBuf>,

    /// Accept any Azure TDX PCR measurements. Useful only to inspect the actual
    /// PCRs returned by the verifier before a measurements file exists.
    #[arg(long)]
    accept_any: bool,
}

#[cfg(target_os = "linux")]
#[derive(Debug, ClapArgs)]
struct BackendArgs {
    /// Optional PCCS URL for DCAP collateral. If omitted, the attestation
    /// backend uses its default DCAP collateral path.
    #[arg(long)]
    pccs_url: Option<String>,

    /// Allow the Azure outdated-TCB override path.
    ///
    /// This exists as a workaround for some Azure v6 TCB collateral. Leave false
    /// unless you are specifically testing that environment.
    #[arg(long)]
    override_azure_outdated_tcb: bool,
}

#[cfg(target_os = "linux")]
#[tokio::main]
async fn main() -> anyhow::Result<()> {
    match Cli::parse().command {
        Command::Roundtrip(args) => roundtrip(args).await,
        Command::Generate(args) => generate(args).await,
        Command::Verify(args) => verify(args).await,
    }
}

#[cfg(target_os = "linux")]
async fn roundtrip(args: RoundtripArgs) -> anyhow::Result<()> {
    let binding = parse_or_default_input(args.binding.input_hex.as_deref())?;
    let policy = load_policy(args.policy).await?;

    println!("Generating Azure TDX + vTPM attestation...");
    let evidence = generate_azure_exchange_message(binding)?;

    if let Some(path) = &args.write_evidence {
        write_exchange_message(path, &evidence).await?;
    }

    println!("Verifying Azure TDX + vTPM attestation...");
    let verified = verify_exchange_message(evidence, binding, policy, args.backend).await?;
    print_verified(&verified);

    Ok(())
}

#[cfg(target_os = "linux")]
async fn generate(args: GenerateArgs) -> anyhow::Result<()> {
    let binding = parse_or_default_input(args.binding.input_hex.as_deref())?;

    println!("Generating Azure TDX + vTPM attestation...");
    let evidence = generate_azure_exchange_message(binding)?;
    write_exchange_message(&args.out, &evidence).await?;

    Ok(())
}

#[cfg(target_os = "linux")]
async fn verify(args: VerifyArgs) -> anyhow::Result<()> {
    let binding = parse_or_default_input(args.binding.input_hex.as_deref())?;
    let policy = load_policy(args.policy).await?;
    let evidence = read_exchange_message(&args.evidence).await?;

    println!("Verifying Azure TDX + vTPM attestation...");
    let verified = verify_exchange_message(evidence, binding, policy, args.backend).await?;
    print_verified(&verified);

    Ok(())
}

/// Azure PCRs as a `BTreeMap`, so output is ordered and diffable across nodes,
/// boots, and builds. The backend hands back a `HashMap`, whose iteration order
/// is not stable.
#[cfg(target_os = "linux")]
fn sorted_azure_pcrs(
    verified: &VerifiedSeismicAttestation,
) -> Option<std::collections::BTreeMap<u32, [u8; 32]>> {
    match verified {
        VerifiedSeismicAttestation::AzureTdx(azure) => Some(
            azure
                .guest_measurements
                .pcrs
                .iter()
                .map(|(index, value)| (*index, *value))
                .collect(),
        ),
        _ => None,
    }
}

#[cfg(target_os = "linux")]
fn print_pcrs(pcrs: &std::collections::BTreeMap<u32, [u8; 32]>) {
    println!("\nQuoted PCRs (SHA-256), {} registers:", pcrs.len());
    for (index, value) in pcrs {
        let marker = if value == &[0u8; 32] { "  (zero)" } else { "" };
        println!("  pcr{index:<2} = {}{marker}", hex::encode(value));
    }
    println!();
}

#[cfg(target_os = "linux")]
fn generate_azure_exchange_message(
    binding: [u8; 64],
) -> anyhow::Result<AttestationExchangeMessage> {
    let evidence = generate_evidence(AttestationType::AzureTdx, binding)?;
    let quote_len = evidence
        .attestation_evidence
        .as_ref()
        .map_or(0, |attested| attested.quote.len());
    println!(
        "Generated {} evidence: {} byte quote",
        evidence.attestation_type(),
        quote_len
    );
    Ok(evidence)
}

#[cfg(target_os = "linux")]
async fn verify_exchange_message(
    evidence: AttestationExchangeMessage,
    binding: [u8; 64],
    policy: SeismicMeasurementPolicy,
    backend: BackendArgs,
) -> anyhow::Result<VerifiedSeismicAttestation> {
    let verified = verify_evidence_with_options(
        evidence,
        binding,
        policy,
        VerifyOptions {
            pccs_url: backend.pccs_url,
            dump_dcap_quotes: false,
            override_azure_outdated_tcb: backend.override_azure_outdated_tcb,
        },
    )
    .await?;
    println!("Verification succeeded.");
    Ok(verified)
}

#[cfg(target_os = "linux")]
async fn load_policy(args: PolicyArgs) -> anyhow::Result<SeismicMeasurementPolicy> {
    if args.accept_any {
        return Ok(
            SeismicMeasurementPolicy::dangerously_accept_any_for_testing(AttestationType::AzureTdx),
        );
    }

    let Some(path) = args.measurements else {
        anyhow::bail!("pass --measurements <file> or --accept-any");
    };
    Ok(SeismicMeasurementPolicy::from_file(path).await?)
}

#[cfg(target_os = "linux")]
async fn write_exchange_message(
    path: &std::path::Path,
    evidence: &AttestationExchangeMessage,
) -> anyhow::Result<()> {
    let bytes = serde_json::to_vec(evidence)?;
    tokio::fs::write(path, bytes).await?;
    println!(
        "Wrote full AttestationExchangeMessage JSON to {}",
        path.display()
    );
    Ok(())
}

#[cfg(target_os = "linux")]
async fn read_exchange_message(
    path: &std::path::Path,
) -> anyhow::Result<AttestationExchangeMessage> {
    let bytes = tokio::fs::read(path).await?;
    let evidence = serde_json::from_slice(&bytes)?;
    println!(
        "Read full AttestationExchangeMessage JSON from {}",
        path.display()
    );
    Ok(evidence)
}

#[cfg(target_os = "linux")]
fn print_verified(verified: &VerifiedSeismicAttestation) {
    // Azure PCRs get a sorted hex table: the derived `HashMap` Debug prints
    // decimal byte arrays in nondeterministic order, which is unreadable and
    // impossible to diff between two captures.
    match sorted_azure_pcrs(verified) {
        Some(pcrs) => {
            println!("Verified Azure TDX attestation.");
            print_pcrs(&pcrs);
        }
        None => println!("Verified Seismic attestation: {verified:#?}"),
    }
}

#[cfg(target_os = "linux")]
fn parse_or_default_input(input_hex: Option<&str>) -> anyhow::Result<[u8; 64]> {
    if let Some(input_hex) = input_hex {
        let bytes = hex::decode(input_hex.trim_start_matches("0x"))?;
        return bytes.try_into().map_err(|bytes: Vec<u8>| {
            anyhow::anyhow!("--input-hex must be 64 bytes, got {}", bytes.len())
        });
    }

    // Deterministic demo-only input. The Azure backend uses the first half as
    // the TPM quote nonce; full 64 bytes are also placed into HCL user-data.
    let mut input = [0u8; 64];
    input[..32].copy_from_slice(b"seismic-demo-azure-vtpm-input!!!");
    input[32..].copy_from_slice(b"do-not-use-this-in-production!!!");
    Ok(input)
}

#[cfg(not(target_os = "linux"))]
fn main() {
    eprintln!("azure_vtpm_roundtrip must be run on a Linux Azure TDX CVM");
    std::process::exit(1);
}
