[package]
name = "boot"
edition.workspace = true
version.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
license.workspace = true
readme.workspace = true

[dependencies]
seismic-enclave = { path = "../enclave" }
tokio.workspace = true

[lints]
workspace = true
