[package]
name = "seismic-enclave-server"
version.workspace = true
edition.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
license.workspace = true
readme.workspace = true
description = "Seismic enclave backend"

[lib]
name = "seismic_enclave_server"
path = "src/lib.rs"

[dependencies]
# attestation-service depends on attestation-agent, ensure versions are compatible when updating
attestation-service = { git = "https://github.com/confidential-containers/trustee", features = ["all-verifier"], rev="1fdd67d"}
attestation-agent = { git = "https://github.com/confidential-containers/guest-components", features = ["az-tdx-vtpm-attester"], rev="e6999a3"}
seismic-enclave = { path = "../enclave" }

aes-gcm.workspace = true
anyhow.workspace = true
az-tdx-vtpm.workspace = true
base64.workspace = true
bincode.workspace = true
byteorder.workspace = true
bytes.workspace = true
env_logger.workspace = true
hex.workspace = true
hkdf.workspace = true
jsonrpsee.workspace = true
kbs-types.workspace = true
log.workspace = true
once_cell.workspace = true
routerify.workspace = true
scroll.workspace = true
secp256k1.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tokio.workspace = true
schnorrkel.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
alloy-sol-types = { version = "0.8", default-features = false }
alloy-primitives = { version = "0.8", default-features = false }
alloy-contract = { version = "0.11", default-features = false }
alloy-provider = "0.8"

[dev-dependencies]
serial_test = "3.2.0"
tempfile = "3.17.1"
reqwest.workspace = true
alloy = { version = "0.11", features = [
    "eips",
    "full",
    "hyper",
    "json-rpc",
    "node-bindings",
    "rpc-client",
     "rpc-types-debug",
    "rpc-types-trace",
] }

[package.metadata.cargo-udeps]
ignore = ["serial_test"]
